# Generated by Django 4.2 on 2023-06-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('lattes', models.URLField(unique=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
